// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./components/system-setting/button/index.vue')['default']
    Carouse: typeof import('./components/system-setting/login-form/carouse.vue')['default']
    Copy_right: typeof import('./components/system-setting/login-form/copy_right.vue')['default']
    Create_edit: typeof import('./components/system-setting/button/create_edit.vue')['default']
    Delete_data_dialog: typeof import('./components/common/delete_data_dialog.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Form: typeof import('./components/system-setting/login-form/form.vue')['default']
    Header_banner: typeof import('./components/system-setting/layout/header_banner.vue')['default']
    Image: typeof import('./components/common/image.vue')['default']
    Left_menu: typeof import('./components/system-setting/layout/left_menu.vue')['default']
    Paging: typeof import('./components/common/paging.vue')['default']
    ProvinceCity: typeof import('./components/data-dictionary/province-city/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Split: typeof import('./components/common/split.vue')['default']
    Tabs: typeof import('./components/system-setting/layout/tabs.vue')['default']
    Title: typeof import('./components/system-setting/login-form/title.vue')['default']
    Upload_file: typeof import('./components/common/upload_file.vue')['default']
    User: typeof import('./components/system-setting/user/index.vue')['default']
  }
}

export {}
